### ISSUE TITLE
Loading module does not create /sys/bus/acpi/devices/ACPI0008:00 with kernel 3.11

### ISSUE THREAD

**Issue by mrueg** [victorenator/als#1]
Hi,
I've loaded the module, but I can't see /sys/bus/acpi/devices/ACPI0008:00. 

If I try to access the module via acpi_call module, it works. Has there anything changed since kernel 3.9?

**Comment by victorenator** [comment]
the module doesn't create device, only attributes.
all devices in  /sys/bus/acpi/devices/ are created by acpi module.

**Comment by mrueg** [comment]
Thanks for your reply. Do you have any idea why my UX32VD doesn't creates that device there?

**Comment by danieleds** [comment]
Works fine here with Linux 3.11.0-15-generic (Ubuntu, UX32VD).
But I observed the same problem on an UX32A some months ago, and I thought it was an issue related to hardware differences.

Is your zenbook recent? Did it come with win7 or win8?

**Comment by victorenator** [comment]
Maybe the path is different.
Exec the command:

```
sudo udevadm info --export-db | grep -C 3 ACPI0008
```

**Comment by mrueg** [comment]
It is a Zenbook UX32VD, it was delivered with Windows 7. There is no ACPI0008, just ACPI0003.
It has the latest bios version 2.14  installed. 
kernel config:
http://bpaste.net/show/176593/

**Comment by mrueg** [comment]
Any idea what is probably missing here?

**Comment by victorenator** [comment]
Device PNP0C02 exists?
Kernel parameter acpi_osi is set?
Send your DSDT table for inspection

**Comment by mrueg** [comment]
Yes looks like it exists:
http://bpaste.net/show/tedBrubPPnoMMetE0K4f/

I set acpi_osi= (without anything set like !Windows2012) in my grub cmdline.

Looking at the decompiled DSDT table: 
        "Device (ALS)
        {
            Method (_HID, 0, NotSerialized)  // _HID: Hardware ID
            {
                If (LGreaterEqual (MSOS (), OSW7))
                {
                    Return ("ACPI0008")
                }
                Else
                {
                    Return ("PNP0C02")
                }"

So I have to set acpi_os to something sane? Any recommendation?

So far, thanks for your help

**Comment by mrueg** [comment]
Dropping the acpi_osi setting from grub cmdline and the device gets created. Thanks! If you've got any recommended setting for acpi_osi, I'd like to know :)

**Comment by mrueg** [comment]
Looks like I got it working with acpi_osi='!Windows2012'

What makes me wonder is, that it always changes back to 0xC8 illuminance (doesn't consider the current light in the room)

**Comment by danieleds** [comment]
I've had the same problem a few weeks ago. I don't know what fixed it, I only observed that it started working again after I booted with an older kernel and then booted again with the latest one. I don't think it's related but it's worth a try.

Steps that works for me:
1. insmod acpi_call.ko
2. insmod als.ko
3. enable als with `echo '\_SB.PCI0.LPCB.EC0.TALS 0x1' > /proc/acpi/call` as root
4. `cat /sys/bus/acpi/devices/ACPI0008\:00/ali`

It works too if I let execute steps 3 and 4 to "Asus Zenbook Ambient Light Sensor Controller" (launch the daemon and then enable the sensor with "-e")

I'm on Linux 3.11.0-17-generic (x64)
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash pcie_aspm=force rootfstype=ext4 acpi_osi='!Windows 2012'"

(yes, I forgot having that value for acpi_osi, this solves at least one mistery)

**Comment by mrueg** [comment]
Yes this works for me now. But the ALS currently always returns 200 (0xC8) as ali value. Does that change for you? Is my sensor broken or disabled?

**Comment by danieleds** [comment]
Yes, that's what I meant.
I don't think your sensor is broken: I had the same problem and it magically disappeared after the steps in my last post's first paragraph (the kernel change).

**Comment by danieleds** [comment]
The "200 (0xC8)" problem reappeared here...

**Comment by globalundo** [comment]
I was stuck with "200 (0xC8)" issue after playing with different "acpi_osi=" arguments and acpi calls. Looks like sensor data update can be blocked by "ALS Control" method. This one resolved the issue for me:

```
echo '\_SB.ATKD.ALSC 0x1' | sudo tee /proc/acpi/call
```

**Comment by mrueg** [comment]
Thanks now the sensor works again.
