### ISSUE TITLE
Issue with Dell XPS 13 (pre 2015)

### ISSUE THREAD

**Issue by lviggiani** [victorenator/als#4]
Hi, after loading the module I see

/sys/bus/acpi/devices/ACPI0008:00

however the directory structure seems to be different by the expected one. It contains:

rwxrwxrwx 1 root root    0  9 ott 12.20 driver -> ../../../../../../../bus/acpi/drivers/acpi_als
-r--r--r-- 1 root root 4096  9 ott 12.22 hid
drwxr-xr-x 5 root root    0  9 ott 12.49 iio:device0
-r--r--r-- 1 root root 4096  9 ott 12.22 modalias
-r--r--r-- 1 root root 4096  9 ott 12.22 path
lrwxrwxrwx 1 root root    0  9 ott 12.49 physical_node -> ../../../../../../pci0000:00/0000:00:1f.0/PNP0C09:00/ACPI0008:00
drwxr-xr-x 2 root root    0  9 ott 12.49 power
-r--r--r-- 1 root root 4096  9 ott 12.22 status
lrwxrwxrwx 1 root root    0  9 ott 12.20 subsystem -> ../../../../../../../bus/acpi
-rw-r--r-- 1 root root 4096  9 ott 12.22 uevent

subfolder "iio:device0" contains "in_illuminance_raw" which seems to give me current raw illuminance value. However gnome 3.18 seems not to detect the sensor and allow automatic display brightness adjustement. I have posted more details here:
http://unix.stackexchange.com/questions/234990/ambient-light-sensor-support-in-gnome-3-18
Can you help me please?

**Comment by victorenator** [comment]
This module isn't iio capable.

Are you sure that you see iio:device0 after loading  this particular module?

**Comment by lviggiani** [comment]
It seems it conflicts with 
/usr/lib/modules/4.2.2-1-ARCH/kernel/drivers/iio/light/acpi-als.ko.gz

If I rmmod that and insmod yours, now ali appears under /sys/bus/acpi/devices/ACPI0008:00

However even if restarting gnome or gdm, the option for automatic brightness adjustment is not there, but perhaps this is out of this scope

**Comment by victorenator** [comment]
GNOME is iio capable.
You need to unload this module and load iio/light/acpi-als.ko . This is right way.

**Comment by victorenator** [comment]
See https://developer.gnome.org/iio-sensor-proxy/1.0/

**Comment by lviggiani** [comment]
When you say "unload this module" you mean yours?
Now I'm the situation that, after boot i see (for example) /sys/bus/acpi/devices/ACPI0008:00/iio:device0/in_illuminance_raw
Is that what you mean?

**Comment by victorenator** [comment]
Yes, unload my module.

Check the value of the net.hadess.SensorProxy.HasAmbientLight dbus property.

**Comment by lviggiani** [comment]
Ok thanks, I made a little search based on your hints and I landed here:
https://github.com/hadess/iio-sensor-proxy
I'm trying to make it work
Thanks again for your help!!!
